# Change these first
owner: bight # Your GitHub username
repo: upptime # Your GitHub repository name

assignees:
  - greatislander

# Add your sites here
sites:
  - name: Bight
    url: https://bight.dev
  - name: CAFÉ ISO
    url: https://cafeiso.com
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bight.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://bight.dev/images/logo.svg
  name: Bight Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
